name: infra

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '**/*.tf' ]

jobs:
  tf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 👇 Add these three import steps here
      - name: Import existing RG (idempotent)
        run: |
          set -e
          terraform init
          terraform state show azurerm_resource_group.rg >/dev/null 2>&1 || \
            terraform import azurerm_resource_group.rg "/subscriptions/c8f13856-1f47-48f4-8103-70800f932e11/resourceGroups/ead-rg"

      - name: Import existing random (so ACR name matches)
        run: |
          # remove any newly-created random from a previous failed apply in this run
          terraform state rm random_integer.rand >/dev/null 2>&1 || true
          terraform import random_integer.rand 6823

      - name: Import existing ACR (idempotent)
        run: |
          terraform state show azurerm_container_registry.acr >/dev/null 2>&1 || \
            terraform import azurerm_container_registry.acr "/subscriptions/c8f13856-1f47-48f4-8103-70800f932e11/resourceGroups/ead-rg/providers/Microsoft.ContainerRegistry/registries/eadacr6823"

      # then proceed as normal
      - name: Terraform Plan
        run: terraform plan -out plan.out

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve plan.out