name: infra
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '**/*.tf' ]

jobs:
  tf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Init (remote backend)
        run: |
          terraform init -input=false -no-color \
            -backend-config="resource_group_name=ead-tfstaterg" \
            -backend-config="storage_account_name=eadtfstate29997" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=ead-infra.tfstate"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out plan.out

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -no-color -auto-approve plan.out
