name: infra-destroy
on:
  workflow_dispatch:

jobs:
  tf-destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init (remote backend)
        run: |
          terraform init -input=false -no-color \
            -backend-config="resource_group_name=ead-tfstaterg" \
            -backend-config="storage_account_name=eadtfstate29997" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=ead-infra.tfstate"

      - name: Terraform Destroy
        run: terraform destroy -input=false -no-color -auto-approve